# Stałe

BOARD_WIDTH = 19
BOARD_HEIGHT = 19

TILE_WIDTH = 32
TILE_HEIGHT = 32

GAME_SPEED = 100
BOT_SPEED = 500
BOMB_SPEED = 3000

EXPLOSION_SPEED = 500
EXPLOSION_LENGTH = 5
EXPLOSION_RAYS = [
    [(ix, 0) for ix in range(1, EXPLOSION_LENGTH + 1)],
    [(ix, 0) for ix in range(-1, -EXPLOSION_LENGTH - 1, -1)],
    [(0, iy) for iy in range(1, EXPLOSION_LENGTH + 1)],
    [(0, iy) for iy in range(-1, -EXPLOSION_LENGTH - 1, -1)],
]


WALL = 0
GRASS = 1
WOOD = 2
PLAYER_FRONT = 3
BOMB = 4
EXPLOSION = 5

DO_NOTHING = 0
MOVE_LEFT = 1
MOVE_UP = 2
MOVE_RIGHT = 3
MOVE_DOWN = 4
PLANT_BOMB = 5
PLAYER_BOMB = 6
